name: " | Dev | Find Services - Regression Pack |"

on:
  workflow_dispatch:

jobs:
  cypress-run:
    environment: famly-experience
    env:
      CYPRESS_BASE_URL: "https://dev.find-support-for-your-family.education.gov.uk/"
    name: " 🛎️ RegressionTests - Family Experience -  Dev Environment "
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - run: date
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v4
        name: cypress
        id: cypress
        continue-on-error: true
        with:
          quiet: true
          browser: chrome
          headless: true
          spec: "cypress/e2e/**/*.cy.js"
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./cypress/reports/

      - name: Checkout reports repo
        uses: actions/checkout@v4
        with:
          ref: reports
          path: reports_repo

      - name: Copy report into reports repo
        run: |
          cd reports_repo
          DATE=$(date +%d-%m-%Y)
          [ -e docs/fx/$DATE ] && rm -rf docs/fx/$DATE
          cp -a ../cypress/reports/html  docs/fx/$DATE
          pushd docs/fx/$DATE
          rm -rf assets
          rm -rf screenshots
          ln -s ../../assets/
          popd
          git add docs .
      - name: Commit todays report to reports branch
        run: |
          cd reports_repo
          git config --local user.email "DFE-Digital+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "report for $(date +%d-%m-%Y)" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: reports
          directory: reports_repo


     